language: node_js
node_js:
  - "6"
install:
  - npm install
  - npm run build
script:
  - bash ./deploy_doc.sh
env:
  global:
  - ENCRYPTION_LABEL: "54b726ebe2ce"
  - COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
